[package]
name = "exex"
version = "0.1.0"
description = "Feature complete OP Stack as an execution extension."
edition = "2021"
license = "MIT"
authors = ["refcell"]
repository = "https://github.com/refcell/cabrinha"
homepage = "https://github.com/refcell/cabrinha"

[dependencies]
anyhow = { version = "1.0.86", default-features = false }
tracing = { version = "0.1.40", default-features = false }
reqwest = "0.12"
tokio = { version = "1.37.0", features = ["full"] }
tracing-subscriber = "0.3.18"
clap = { version = "4.5.4", features = ["derive", "env"] }
serde = { version = "1.0.198", features = ["derive"] }
eyre = "0.6.12"
async-trait = "0.1.68"

# Kona Deps
kona-derive = { version = "0.0.2", features = ["serde", "k256", "online"] }

# Reth Deps
reth = { git = "https://github.com/paradigmxyz/reth", branch = "main", version = "1.0.0" }
reth-exex = { git = "https://github.com/paradigmxyz/reth", branch = "main", version = "1.0.0" }
reth-node-api = { git = "https://github.com/paradigmxyz/reth", branch = "main", version = "1.0.0" }
reth-primitives = { git = "https://github.com/paradigmxyz/reth", branch = "main", version = "1.0.0" }
reth-node-ethereum = { git = "https://github.com/paradigmxyz/reth", branch = "main", version = "1.0.0" }
reth-provider = { git = "https://github.com/paradigmxyz/reth", branch = "main", version = "1.0.0" }
reth-tracing = { git = "https://github.com/paradigmxyz/reth", branch = "main", version = "1.0.0" }

# Alloy Deps
alloy-provider = { version = "0.1", default-features = false }
alloy-rpc-types = { version = "0.1" }
alloy-transport = { version = "0.1", default-features = false }
alloy-primitives = { version = "0.7", features = ["serde"] }
alloy-eips = { version = "0.1", default-features = false }
alloy-consensus = { version = "0.1", default-features = false }
alloy-rlp = "0.3.4"
